<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=gb2312">
  <title>PHP 7 错误处理</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="language.errors.basics.html">? 基础概要</a></li>
      <li style="float: right;"><a href="language.exceptions.html">异常 ?</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="language.errors.html">错误</a></li>
    <li>PHP 7 错误处理</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="language.errors.php7" class="sect1">
 <h2 class="title">PHP 7 错误处理</h2>

 <p class="para">
  PHP 7 改变了大多数错误的报告方式。不同于传统（PHP 5）的错误报告机制，现在大多数错误被作为
  <a href="class.error.html" class="classname">Error</a> 异常抛出。
 </p>

 <p class="para">
  这种 <a href="class.error.html" class="classname">Error</a> 异常可以像 <a href="class.exception.html" class="classname">Exception</a>
  异常一样被第一个匹配的 <code class="literal">try</code> / <code class="literal">catch</code>
  块所捕获。如果没有匹配的
  <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>
  块，则调用异常处理函数（事先通过 <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> 注册）进行处理。
  如果尚未注册异常处理函数，则按照传统方式处理：被报告为一个致命错误（Fatal Error）。
 </p>

 <p class="para">
  <a href="class.error.html" class="classname">Error</a> 类并非继承自 <a href="class.exception.html" class="classname">Exception</a>
  类，所以不能用 <code class="code">catch (Exception $e) { ... }</code> 来捕获
  <a href="class.error.html" class="classname">Error</a>。你可以用
  <code class="code">catch (Error $e) { ... }</code>，或者通过注册异常处理函数（
  <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span>）来捕获 <a href="class.error.html" class="classname">Error</a>。
 </p>

 <div class="sect2" id="language.errors.php7.hierarchy">
  <h3 class="title"><a href="class.error.html" class="classname">Error</a> 层次结构</h3>

  <ul class="itemizedlist">
   <li class="listitem">
    <span class="simpara"><a href="class.throwable.html" class="classname">Throwable</a></span>
    <ul class="itemizedlist">
     <li class="listitem">
      <span class="simpara"><a href="class.error.html" class="classname">Error</a></span>
      <ul class="itemizedlist">
       <li class="listitem">
        <span class="simpara"><a href="class.arithmeticerror.html" class="classname">ArithmeticError</a></span>
        <ul class="itemizedlist">
         <li class="listitem">
          <span class="simpara"><a href="class.divisionbyzeroerror.html" class="classname">DivisionByZeroError</a></span>
         </li>
        </ul>
       </li>
       <li class="listitem">
        <span class="simpara"><a href="class.assertionerror.html" class="classname">AssertionError</a></span>
       </li>
       <li class="listitem">
        <span class="simpara"><a href="class.compileerror.html" class="classname">CompileError</a></span>
        <ul class="itemizedlist">
         <li class="listitem">
          <span class="simpara"><a href="class.parseerror.html" class="classname">ParseError</a></span>
         </li>
        </ul>
       </li>
       <li class="listitem">
        <span class="simpara"><a href="class.typeerror.html" class="classname">TypeError</a></span>
        <ul class="itemizedlist">
         <li class="listitem">
          <span class="simpara"><a href="class.argumentcounterror.html" class="classname">ArgumentCountError</a></span>
         </li>
        </ul>
       </li>
       <li class="listitem">
        <span class="simpara"><a href="class.valueerror.html" class="classname">ValueError</a></span>
       </li>
       <li class="listitem">
        <span class="simpara"><a href="class.unhandledmatcherror.html" class="classname">UnhandledMatchError</a></span>
       </li>
       <li class="listitem">
        <span class="simpara"><a href="class.fibererror.html" class="classname">FiberError</a></span>
       </li>
      </ul>
     </li>
     <li class="listitem">
      <span class="simpara"><a href="class.exception.html" class="classname">Exception</a></span>
      <ul class="itemizedlist">
       <li class="listitem">
        <span class="simpara">...</span>
       </li>
      </ul>
     </li>
    </ul>
   </li>
  </ul>
 </div>
</div><div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="124428""></a>
  <div class="note">
   <strong class="user">diogoca at gmail dot com</strong>
   <a href="#124428" class="date">24-Nov-2019 02:38</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
<span class="default">&lt;?php<br />
<br />
set_error_handler</span><span class="keyword">(function(</span><span class="default">int $number</span><span class="keyword">, </span><span class="default">string $message</span><span class="keyword">) {<br />
&nbsp;&nbsp; echo </span><span class="string">"Handler captured error </span><span class="default">$number</span><span class="string">: '</span><span class="default">$message</span><span class="string">'" </span><span class="keyword">. </span><span class="default">PHP_EOL&nbsp; </span><span class="keyword">;<br />
});<br />
<br />
try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="default">$x</span><span class="keyword">; </span><span class="comment"># notice, handled on callable<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">pg_exec</span><span class="keyword">(</span><span class="default">null</span><span class="keyword">, </span><span class="default">null</span><span class="keyword">); </span><span class="comment"># warning, handled on callable<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">fho</span><span class="keyword">(); </span><span class="comment"># fatal error, stop running and catched<br />
</span><span class="keyword">} catch (</span><span class="default">Throwable $e</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"Captured Throwable: " </span><span class="keyword">. </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() . </span><span class="default">PHP_EOL</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="default">?&gt;<br />
</span><br />
set_error_handler will also works without try and catch</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="121497""></a>
  <div class="note">
   <strong class="user">ryan dot jentzsch@{gmail} dot com</strong>
   <a href="#121497" class="date">08-Aug-2017 09:41</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
An excellent blog post on the difference between exceptions, throwables and how PHP 7 handles these can be found here: https://trowski.com/2015/06/24/throwable-exceptions-and-errors-in-php7/</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="120257""></a>
  <div class="note">
   <strong class="user">lubaev dot ka at gmail dot com</strong>
   <a href="#120257" class="date">01-Dec-2016 05:16</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
php 7.1<br />
<br />
try {<br />
&nbsp;&nbsp; // Code that may throw an Exception or ArithmeticError.<br />
} catch (ArithmeticError | Exception $e) {<br />
&nbsp;&nbsp; // pass<br />
}</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="119652""></a>
  <div class="note">
   <strong class="user">demis dot palma at tiscali dot it</strong>
   <a href="#119652" class="date">26-Jul-2016 11:04</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Throwable does not work on PHP 5.x.<br />
<br />
To catch both exceptions and errors in PHP 5.x and 7, add a catch block for Exception AFTER catching Throwable first.<br />
Once PHP 5.x support is no longer needed, the block catching Exception can be removed.<br />
<br />
try<br />
{<br />
&nbsp;&nbsp; // Code that may throw an Exception or Error.<br />
}<br />
catch (Throwable $t)<br />
{<br />
&nbsp;&nbsp; // Executed only in PHP 7, will not match in PHP 5<br />
}<br />
catch (Exception $e)<br />
{<br />
&nbsp;&nbsp; // Executed only in PHP 5, will not be reached in PHP 7<br />
}</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="118610""></a>
  <div class="note">
   <strong class="user">hungry dot rahly at gmail dot com</strong>
   <a href="#118610" class="date">08-Jan-2016 12:26</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
You can catch both exceptions and errors by catching(Throwable)</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
</div></div></body></html>
